### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NoteBlockMR** [ETO-QSH/RedstoneMusicETO#1]
能知道该怎么做吗？

**Comment by ETO-QSH** [comment]
@NoteBlockMR 这个项目是比较早的时候写的，它目前需要更新，因为我找到了更好的实现方法，计划将在一周左右提交更新。现在它依靠使用mcfunction进行创建结构，效率比较低，我计划将方块直接写入mca文件。

如果你想先看一下现在的效果，你可以看到music.py文件，安装它的依赖库mido，file变量是midi文件路径(需要比较规整的)，直接运行可以在py文件路径得到一大堆.mcfunction文件，
![image](https://github.com/user-attachments/assets/341e1c00-2bc1-4edd-9933-1227d509ff25)
我们这样添加一个datapacks来得到一个命令(可以看到我生成路径的功能都没有写)，使用这个命令/function redstone_music:test_begin他会召唤一个结构，你放红石火把之后它会补全结构(需要等待一段时间，也就是我为什么将放弃这个方法)
![2024-07-18_16 52 15](https://github.com/user-attachments/assets/25f56965-2095-47b9-b8da-8925014489d1)
。结构完成后会给你提示就生成了一个红石音乐结构(并不美观我还需要进行修饰)。

或者更简单一点，我提供的zip里面是一个生成好的datapacks。因为很久没有更新，pianonote.jar我的版本是1.18.2的，smooth-chunks-1.0.0.jar不需要。如果你运行了music.py文件，print(bpm, ('%.2f' % (bpm/v)), len(new_new_new_List))这里会返回一个速度，意味着你应该将我的世界的运行速度调快多少使得和原曲速度一致，可以使用CE，补全结构也可以使用CE加速。

如果你希望使用这个项目，最好就是等待更新结束，它会以更合理高效的方式完成工作。

**Comment by ETO-QSH** [comment]
zip里面的不是我提供的两个midi的，另外相关的材质包我也没有附上去（我搞丢了qwq）

**Comment by NoteBlockMR** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/82017b6c-1778-46e2-a05e-550aee33bf9e)
error?????

**Comment by NoteBlockMR** [comment]
![Screenshot_3](https://github.com/user-attachments/assets/83135994-8e68-4a67-bfa4-6161c15f3883)
end function command test_begin_? not

**Comment by ETO-QSH** [comment]
@NoteBlockMR 你只需要使用这个命令/function redstone_music:test_begin，后面的命令由命令方块运行（红石火把放在命令方块和那个观察者后面之间的位置，这是一个高频电路）。

**Comment by NoteBlockMR** [comment]
So that command doesn't work

**Comment by NoteBlockMR** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/3d1f17cd-df70-4c06-921f-cabac8318193)
ok??

**Comment by ETO-QSH** [comment]
@NoteBlockMR I think you should open the text box with the T key and use /function redstone_music:test_begin inside. 
/function redstone_music:test_begin NOT /function redstone_music:test_begin_0. 
Try in new world best

**Comment by NoteBlockMR** [comment]
I've already tried that, but it doesn't work

**Comment by NoteBlockMR** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/69241b84-f49d-4641-b489-3cab9f54f2c6)

**Comment by ETO-QSH** [comment]
@NoteBlockMR 
![image](https://github.com/user-attachments/assets/09794395-819a-421d-a8fe-724c58de0c15)
May I ask if you have loaded my mod correctly? I need to fill this box in my command. If the mod is not loaded correctly, it will be unknoun function

**Comment by NoteBlockMR** [comment]
hay Forge?? and Fabric??

**Comment by ETO-QSH** [comment]
@NoteBlockMR Forge 1.18.2

**Comment by NoteBlockMR** [comment]
![Screenshot_6](https://github.com/user-attachments/assets/42e92128-21b9-4ab7-a578-1a5642a66abc)
![Screenshot_7](https://github.com/user-attachments/assets/b0623550-5bac-49bd-ad18-f0bc27be74ee)

**Comment by ETO-QSH** [comment]
@NoteBlockMR [pianonote.jar](https://github.com/ETO-QSH/RedstoneMusicETO/blob/main/pianonote.jar)
I haven't published it yet, in my project, in the mod(s) folder is fine

**Comment by NoteBlockMR** [comment]
working!! good!!

**Comment by ETO-QSH** [comment]
@NoteBlockMR I wonder if you have used CE to adjust the speed to achieve better results. My next update will eliminate the part of running commands in the game to make it easier.Thank you for using it!
